In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [5]:
df=pd.read_csv(r"C:\Users\Shiva kumar\OneDrive\Desktop\Project\data\youtube_channels_1M_clean.csv")
df.head()

,channel_id,channel_link,channel_name,subscriber_count,banner_link,description,keywords,avatar,country,total_views,total_videos,join_date,mean_views_last_30_videos,median_views_last_30_videos,std_views_last_30_videos,videos_per_week
0,UCUMHFa347GD8EIRaVVuxR8Q,/@TonettaClay,Tonetta Clay,781,https://yt3.googleusercontent.com/bj2C0MOj3SMi...,My name is Tonetta or Toni for short and I'm d...,NaN,https://yt3.googleusercontent.com/cUmKB4Zet1SX...,NaN,227567.0,1984.0,2015-12-08,10.866667,6.5,13.922963,1.50
1,UC28mqg7IlYWEhrZwHb72IQA,/@FoodnHappinessVeena,Food 'n' Happiness,0,NaN,"Hello viewers.\n I am Veena from Mangalore, Ka...","food n happiness, food and happiness, food, Fo...",https://yt3.googleusercontent.com/lY_u-8bLWNgA...,India,592961.0,158.0,2020-05-08,1448.066667,1510.0,869.364401,0.00
2,UCoLwWY9zQ7Jp8aDtYUszmYg,/@TimShieff,Tim Shieff,166000,https://yt3.googleusercontent.com/2KC8Lj8RF3uF...,The journey of rediscovery.\n\nhttps://rdscvr.com,"Tim, shieff, timothy, health, human, spiritual...",https://yt3.googleusercontent.com/-aNZLP23AnkX...,United Kingdom,27250763.0,372.0,2006-03-19,5456.933333,3430.0,4322.803149,0.00
3,UCAQOeJwsgBMC74-OjjcQcJA,/@JerryAndJulieMusic,Jerry & Julie Music,1090,https://yt3.googleusercontent.com/dI6Oq0iOhx-c...,Welcome to Jerry & Julie Music. We hope you w...,"jerryandjuliemusic, jerryspianobar, juliesguit...",https://yt3.googleusercontent.com/c41pe3_aA75h...,United States,339906.0,913.0,2010-03-27,75.966667,47.5,113.374448,4.00
4,UCOqwGhI1AmpWwxMYw9D_fqw,/@KichuandYugiMagizhakam,Kichu and Yugi Magizhakam,1160,https://yt3.googleusercontent.com/CXrATV8NKPRg...,Hi friends welcome to my channel...I'm Devi mo...,NaN,https://yt3.googleusercontent.com/FDA5pc1ZQ5jT...,NaN,288328.0,476.0,2023-12-21,85.700000,66.0,72.032007,1.25

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095242 entries, 0 to 1095241
Data columns (total 16 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   channel_id                   1095242 non-null  object
 1   channel_link                 1095242 non-null  object
 2   channel_name                 1095182 non-null  object
 3   subscriber_count             1095242 non-null  int64
 4   banner_link                  766877 non-null   object
 5   description                  819743 non-null   object
 6   keywords                     547203 non-null   object
 7   avatar                       1095242 non-null  object
 8   country                      620059 non-null   object
 9   total_views                  1094490 non-null  float64
 10  total_videos                 1094985 non-null  float64
 11  join_date                    1095220 non-null  object
 12  mean_views_last_30_videos    1059085 non-null  float64
 13  median_views_last_30_videos  1059085 non-null  float64
 14  std_views_last_30_videos     1059085 non-null  float64
 15  videos_per_week              1059085 non-null  float64
dtypes: float64(6), int64(1), object(9)
memory usage: 133.7+ MB

In [7]:
df.describe()

,subscriber_count,total_views,total_videos,mean_views_last_30_videos,median_views_last_30_videos,std_views_last_30_videos,videos_per_week
count,1.095242e+06,1.094490e+06,1.094985e+06,1.059085e+06,1.059085e+06,1.059085e+06,1.059085e+06
mean,6.718270e+04,2.558005e+07,4.139291e+02,4.173914e+04,1.937563e+04,6.503651e+04,6.252839e-01
std,8.592589e+05,5.176393e+08,3.910517e+03,1.322847e+06,8.900375e+05,1.908503e+06,1.535874e+00
min,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,3.300000e+01,8.288000e+03,2.300000e+01,8.742857e+01,4.000000e+01,7.678400e+01,0.000000e+00
50%,3.730000e+02,8.386200e+04,8.400000e+01,4.253333e+02,1.455000e+02,5.438977e+02,0.000000e+00
75%,2.900000e+03,6.678882e+05,2.670000e+02,2.587567e+03,7.525000e+02,4.089039e+03,5.000000e-01
max,2.440000e+08,1.788442e+11,1.248360e+06,6.889384e+08,6.712840e+08,1.069565e+09,7.500000e+00

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.isnull().sum().sort_values(ascending=False)

keywords                       548039
country                        475183
banner_link                    328365
description                    275499
mean_views_last_30_videos       36157
median_views_last_30_videos     36157
std_views_last_30_videos        36157
videos_per_week                 36157
total_views                       752
total_videos                      257
channel_name                       60
join_date                          22
avatar                              0
channel_id                          0
channel_link                        0
subscriber_count                    0
dtype: int64

In [12]:
#Droping useless columns
df.drop(columns=[
'keywords',
'country',
'banner_link',
'description',
'avatar',
'channel_id',
'channel_link'
], inplace=True)

In [13]:
#handling missing numerical values
num_cols = [
'mean_views_last_30_videos',
'median_views_last_30_videos',
'std_views_last_30_videos',
'videos_per_week',
'total_views',
'total_videos'
]

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [14]:
#Handling join_date
df['join_date'] = pd.to_datetime(df['join_date'])

df['channel_age'] = 2025 - df['join_date'].dt.year

In [15]:
df.drop(columns=['join_date'], inplace=True)

In [16]:
#Handling missing channel names
df.dropna(subset=['channel_name'], inplace=True)

In [17]:
df.isnull().sum()

channel_name                    0
subscriber_count                0
total_views                     0
total_videos                    0
mean_views_last_30_videos       0
median_views_last_30_videos     0
std_views_last_30_videos        0
videos_per_week                 0
channel_age                    22
dtype: int64

In [19]:
df['channel_age'] = df['channel_age'].fillna(df['channel_age'].median())

In [20]:
df.isnull().sum()

channel_name                   0
subscriber_count               0
total_views                    0
total_videos                   0
mean_views_last_30_videos      0
median_views_last_30_videos    0
std_views_last_30_videos       0
videos_per_week                0
channel_age                    0
dtype: int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1095182 entries, 0 to 1095241
Data columns (total 9 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   channel_name                 1095182 non-null  object
 1   subscriber_count             1095182 non-null  int64
 2   total_views                  1095182 non-null  float64
 3   total_videos                 1095182 non-null  float64
 4   mean_views_last_30_videos    1095182 non-null  float64
 5   median_views_last_30_videos  1095182 non-null  float64
 6   std_views_last_30_videos     1095182 non-null  float64
 7   videos_per_week              1095182 non-null  float64
 8   channel_age                  1095182 non-null  float64
dtypes: float64(7), int64(1), object(1)
memory usage: 83.6+ MB

In [22]:
df.shape

(1095182, 9)

In [23]:
df.describe()

,subscriber_count,total_views,total_videos,mean_views_last_30_videos,median_views_last_30_videos,std_views_last_30_videos,videos_per_week,channel_age
count,1.095182e+06,1.095182e+06,1.095182e+06,1.095182e+06,1.095182e+06,1.095182e+06,1.095182e+06,1.095182e+06
mean,6.718622e+04,2.556390e+07,4.138509e+02,4.037727e+04,1.874175e+04,6.291026e+04,6.046292e-01,8.665234e+00
std,8.592823e+05,5.174761e+08,3.910162e+03,1.300884e+06,8.752536e+05,1.876822e+06,1.514410e+00,4.724011e+00
min,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
25%,3.300000e+01,8.306000e+03,2.300000e+01,9.260000e+01,4.200000e+01,8.259555e+01,0.000000e+00,5.000000e+00
50%,3.730000e+02,8.386200e+04,8.400000e+01,4.253333e+02,1.455000e+02,5.438977e+02,0.000000e+00,8.000000e+00
75%,2.900000e+03,6.666632e+05,2.670000e+02,2.400117e+03,6.980000e+02,3.779276e+03,2.500000e-01,1.200000e+01
max,2.440000e+08,1.788442e+11,1.248360e+06,6.889384e+08,6.712840e+08,1.069565e+09,7.500000e+00,2.000000e+01